/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rangahau_ExternalTimerCard */

#ifndef _Included_rangahau_ExternalTimerCard
#define _Included_rangahau_ExternalTimerCard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rangahau_ExternalTimerCard
 * Method:    nativeClosePort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_rangahau_ExternalTimerCard_nativeClosePort
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_ExternalTimerCard
 * Method:    nativeOpenPort
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_rangahau_ExternalTimerCard_nativeOpenPort
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rangahau_ExternalTimerCard
 * Method:    nativeWriteData
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_rangahau_ExternalTimerCard_nativeWriteData
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     rangahau_ExternalTimerCard
 * Method:    nativeReadStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_rangahau_ExternalTimerCard_nativeReadStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_ExternalTimerCard
 * Method:    nativeReadControl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_rangahau_ExternalTimerCard_nativeReadControl
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_ExternalTimerCard
 * Method:    nativeWriteControl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_rangahau_ExternalTimerCard_nativeWriteControl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     rangahau_ExternalTimerCard
 * Method:    nativeWriteControlBit
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_rangahau_ExternalTimerCard_nativeWriteControlBit
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
