/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rangahau_GpsClock */

#ifndef _Included_rangahau_GpsClock
#define _Included_rangahau_GpsClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rangahau_GpsClock
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rangahau_GpsClock_nativeOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rangahau_GpsClock
 * Method:    nativeClose
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rangahau_GpsClock_nativeClose
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rangahau_GpsClock
 * Method:    nativeWrite
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_rangahau_GpsClock_nativeWrite
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     rangahau_GpsClock
 * Method:    nativeRead
 * Signature: (Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_rangahau_GpsClock_nativeRead
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     rangahau_GpsClock
 * Method:    nativeFindAllDeviceIdentifiers
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_rangahau_GpsClock_nativeFindAllDeviceIdentifiers
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
