/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rangahau_RoperCamera */

#ifndef _Included_rangahau_RoperCamera
#define _Included_rangahau_RoperCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rangahau_RoperCamera
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_rangahau_RoperCamera_nativeOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rangahau_RoperCamera
 * Method:    nativeClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_rangahau_RoperCamera_nativeClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_RoperCamera
 * Method:    nativeGetWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_rangahau_RoperCamera_nativeGetWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_RoperCamera
 * Method:    nativeGetHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_rangahau_RoperCamera_nativeGetHeight
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_RoperCamera
 * Method:    nativeStartAcquisition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_rangahau_RoperCamera_nativeStartAcquisition
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_RoperCamera
 * Method:    nativeStopAcquisition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_rangahau_RoperCamera_nativeStopAcquisition(JNIEnv*, jobject, jint);

/*
 * Class:     rangahau_RoperCamera
 * Method:    nativeIsImageReady
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_rangahau_RoperCamera_nativeIsImageReady
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_RoperCamera
 * Method:    nativeGetImage
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_rangahau_RoperCamera_nativeGetImage
  (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
