/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rangahau_SerialPortDevice */

#ifndef _Included_rangahau_SerialPortDevice
#define _Included_rangahau_SerialPortDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rangahau_SerialPortDevice
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_rangahau_SerialPortDevice_nativeOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rangahau_SerialPortDevice
 * Method:    nativeClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_rangahau_SerialPortDevice_nativeClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_SerialPortDevice
 * Method:    nativeBytesAvailable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_rangahau_SerialPortDevice_nativeBytesAvailable
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_SerialPortDevice
 * Method:    nativeReadByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_rangahau_SerialPortDevice_nativeReadByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     rangahau_SerialPortDevice
 * Method:    nativeWriteByte
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_rangahau_SerialPortDevice_nativeWriteByte
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     rangahau_SerialPortDevice
 * Method:    nativeFlush
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_rangahau_SerialPortDevice_nativeFlush
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
